// <auto-generated />
using System;
using LocalAIAgent.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalAIAgent.API.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260207192737_FixFKs2")]
    partial class FixFKs2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationClientDataJson")
                        .HasColumnType("BLOB");

                    b.Property<string>("AttestationFormat")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationObject")
                        .HasColumnType("BLOB");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Transports")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserFido2Id")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fido2Credentials");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Fido2Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fido2Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Dislikes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "Owner")
                        .WithMany("Fido2Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", null)
                        .WithMany()
                        .HasForeignKey("Fido2Id");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("LocalAIAgent.API.Infrastructure.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Fido2Credentials");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
