// <auto-generated />
using System;
using LocalAIAgent.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalAIAgent.API.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260817155028_LocalServerInvitations")]
    partial class LocalServerInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.AiSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKeyCiphertext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FrequencyPenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PresencePenalty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiSettings");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.ArticleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleLink", "TargetLanguage")
                        .IsUnique();

                    b.ToTable("ArticleTranslations");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.CustomFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFetchErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Urls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPreferencesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferencesId");

                    b.ToTable("CustomFeeds");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationClientDataJson")
                        .HasColumnType("BLOB");

                    b.Property<string>("AttestationFormat")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationObject")
                        .HasColumnType("BLOB");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Transports")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserFido2Id")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fido2Credentials");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RedeemedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RedeemedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.NewsEvaluationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleTopic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relevancy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseInDataset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPreferencesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferencesId", "ArticleLink")
                        .IsUnique();

                    b.ToTable("NewsEvaluationEntries");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Fido2Id")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("DisabledFeedSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Dislikes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.CustomFeed", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.UserPreferences", "UserPreferences")
                        .WithMany("CustomFeeds")
                        .HasForeignKey("UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "Owner")
                        .WithMany("Fido2Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Invitation", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "CreatedByUser")
                        .WithMany("CreatedInvitations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "RedeemedByUser")
                        .WithMany()
                        .HasForeignKey("RedeemedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("RedeemedByUser");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.NewsEvaluationEntry", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.UserPreferences", "UserPreferences")
                        .WithMany("EvaluationEntries")
                        .HasForeignKey("UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("LocalAIAgent.API.Infrastructure.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Navigation("CreatedInvitations");

                    b.Navigation("Fido2Credentials");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.Navigation("CustomFeeds");

                    b.Navigation("EvaluationEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
