// <auto-generated />
using System;
using LocalAIAgent.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalAIAgent.API.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Fido2NetLib.Fido2User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB")
                        .HasJsonPropertyName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.HasKey("Id");

                    b.ToTable("Fido2User");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationClientDataJson")
                        .HasColumnType("BLOB");

                    b.Property<string>("AttestationFormat")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AttestationObject")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("RegDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Transports")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserId1")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Fido2Credentials");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Fido2Id")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Dislikes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.Fido2Credential", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", null)
                        .WithMany("Fido2Credentials")
                        .HasForeignKey("UserId");

                    b.HasOne("Fido2NetLib.Fido2User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.UserPreferences", b =>
                {
                    b.HasOne("LocalAIAgent.API.Infrastructure.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("LocalAIAgent.API.Infrastructure.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalAIAgent.API.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Fido2Credentials");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
