<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../LocalAIAgent.Application/News/PublicNetworkHttpHandler.cs" Link="PublicNetworkHttpHandler.cs" />
  </ItemGroup>
</Project>
