name: Automatically Tag Release Branch

on:
   push:
     branches: [ "rel/*" ]
     
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract version from branch name
        run: |
          BRANCH_NAME=${{ github.ref }}
          VERSION=${BRANCH_NAME#refs/heads/rel/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
            echo "Tag $VERSION already exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Create tag
        if: env.exists == 'false'
        run: |
          git tag $VERSION
          git push origin $VERSION
