name: Auto Tag Releases

on:
   push:
     branches: [ "rel/*" ]
     
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract version from branch name
        run: |
          BRANCH_NAME=${{ github.ref }}
          VERSION=${BRANCH_NAME#refs/heads/rel/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag $VERSION
          git push origin $VERSION
