name: Release Console App

on:
  push:
    tags:
      - "*"

jobs:

  build:
  
    runs-on: ubuntu-latest

    env:
      Solution_Name: ${{ vars.SOLUTION_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish as Single Executable
      run: dotnet publish -c Release -r win-x64 --self-contained /p:PublishSingleFile=true /p:UseAppHost=true

    - name: Rename the executable
      run: mv /home/runner/work/Local-AI-Agent/Local-AI-Agent/LocalAIAgent.App/bin/Release/net9.0/win-x64/publish/LocalAIAgent.App.exe /home/runner/work/Local-AI-Agent/Local-AI-Agent/LocalAIAgent.App/bin/Release/net9.0/win-x64/publish/LocalAIAgent.exe

    - name: Remove the .pdp file
      run: rm /home/runner/work/Local-AI-Agent/Local-AI-Agent/LocalAIAgent.App/bin/Release/net9.0/win-x64/publish/LocalAIAgent.App.pdb

    - name: Zip the publish folder
      run: zip -j LocalAIAgent.zip /home/runner/work/Local-AI-Agent/Local-AI-Agent/LocalAIAgent.App/bin/Release/net9.0/win-x64/publish/LocalAIAgent.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: ${{ env.Solution_Name }}
       path: LocalAIAgent.zip

    - name: Create GitHub Release with ZIP
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          New release created!
          - Tag: ${{ github.ref_name }}
          - Includes an auto-generated ZIP file.
        files: LocalAIAgent.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
