name: Code Formatting Check

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 9.0.x
         
      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test

      - name: Check Code Quality
        run: dotnet format --verify-no-changes
