name: Dependency Security Check

on:
  pull_request

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Check .NET dependencies for vulnerabilities (exclude ReactJS project)
        run: |
              for proj in $(find . -name '*.csproj'); do
                dotnet list "$proj" package --vulnerable
              done